### ISSUE TITLE
Remove dependency on hacked version of flex

### ISSUE THREAD

**Issue by pebbe** [rug-compling/dbxml#1]
When someone downloads dbxml with git, it is not certain in what order the files are installed. There are some files that depends on other files, all included, that are going to get rebuilt if those other files have a newer time stamp.

Some of these builds use a patched version of flex. But that version of flex is not provided, nor generally available. These dependencies should be removed.

**Comment by danieldk** [comment]
I was running into this issue again while compiling DBXML manually on Fedora. I am not really sure if the flex files use special features from this patched version and trying to find out does not sound like an interesting way to spend time. So I am proposing a simpler solution: in the `buildall.sh` script, we just `touch` the files that are generated through flex/yacc. Then the generated files are always newer than their flex/yacc sources and `make` will not attempt to regenerate them.

What do you think?

**Comment by pebbe** [comment]
Sounds good.

There may be similar problems with other files. On a recent install on Ubuntu Xenial I needed this:

    touch xqilla/src/parser/XQParser.cpp xqilla/src/parser/XQParser.hpp
    touch xqilla/src/lexer/XQLexer.cpp xqilla/src/lexer/XQLexer.hpp
    chmod +x dbxml/dist/s_paths
    ./buildall.sh --prefix=$HOME/dbxml --with-configure-env="CXXFLAGS=-std=c++03"
