### ISSUE TITLE
Compiler errors with newer versions of g++

### ISSUE THREAD

**Issue by pebbe** [rug-compling/dbxml#2]
To compile this on Debian 9, you need to add the following option to the build script:
```
 --with-configure-env="CXXFLAGS=-std=c++03"
```
I guess the same goes for any platform that uses a recent version of g++.  
Perhaps the build script could be fixed to include this setting by default when available?

**Comment by danieldk** [comment]
On 22. Jun 2017, at 18:40, Peter Kleiweg <notifications@github.com> wrote:
> To compile this on Debian 9, you need to add the following option to the build script:
>  --with-configure-env="CXXFLAGS=-std=c++03"
> I guess the same goes for any platform that uses a recent version of g++.
> Perhaps the build script could be fixed to include this setting by default when available?
> 
Sounds good! Though it’d be good to check clang as well.
